'use client';
import Link from 'next/link'; import { useState } from 'react'; import { Building2, Network, UsersRound } from 'lucide-react';
type Department = { id: string; name: string; code: string; hodId: string | null }; type User = { id: string; username: string; fullName: string | null; position: string | null; isActive: boolean; isApprover: boolean; isAllBranches: boolean; departmentId: string | null }; type Branch = { id: string; name: string; code: string; generalManagerId: string | null; departments: Department[]; users: User[] };
const selectClass = 'px-3 py-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-950';
export function BranchDetailClient({ branch }: { branch: Branch }) {
  const approvers = branch.users.filter((u) => u.isActive && u.isApprover);
  const mutate = async (url: string, body: unknown) => { const response = await fetch(url, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (response.ok) location.reload(); else alert((await response.json()).error); };
  return <div className="mt-6 space-y-5">
    <section className="rounded-2xl border bg-white dark:bg-slate-900 dark:border-slate-800 p-5"><div className="flex items-center gap-2 mb-4"><Building2 className="text-blue-600"/><h2 className="font-bold text-lg">ผู้จัดการทั่วไป (GM)</h2></div><select className={selectClass} value={branch.generalManagerId ?? ''} onChange={(e) => void mutate(`/api/admin/branches/${branch.id}`, { generalManagerId: e.target.value || null })}><option value="">ยังไม่กำหนด GM</option>{approvers.map((u) => <option key={u.id} value={u.id}>{u.fullName ?? u.username}</option>)}</select><p className="mt-2 text-xs text-slate-500">จะแทน HOD อัตโนมัติเมื่อแผนกไม่มีหัวหน้าแผนก</p></section>
    <section className="rounded-2xl border bg-white dark:bg-slate-900 dark:border-slate-800 p-5"><div className="flex items-center gap-2 mb-2"><Network className="text-blue-600"/><h2 className="font-bold text-lg">Department และ HOD ของสาขา</h2></div><p className="text-sm text-slate-500">แผนกส่วนกลางจะถูกเพิ่มให้ทุกสาขาอัตโนมัติ โดยแต่ละสาขากำหนด HOD ของตนเองได้</p>{branch.departments.length === 0 ? <p className="mt-4 text-slate-500">ยังไม่มี Department ที่เปิดใช้งาน</p> : <div className="mt-4 space-y-3">{branch.departments.map((dept) => <DepartmentRow key={dept.id} branchId={branch.id} department={dept} approvers={approvers}/>)}</div>}</section>
    <section className="rounded-2xl border bg-white dark:bg-slate-900 dark:border-slate-800 p-5"><div className="flex justify-between items-center"><div className="flex items-center gap-2"><UsersRound className="text-blue-600"/><h2 className="font-bold text-lg">ผู้ใช้งานในสาขาและผู้บริหารส่วนกลาง ({branch.users.length})</h2></div><Link href="/e-approve/admin/approvers" className="px-3 py-2 rounded-lg bg-blue-600 text-white text-sm">จัดการ Approvers</Link></div><div className="mt-4 grid md:grid-cols-2 gap-2">{branch.users.map((u) => <div key={u.id} className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800"><b>{u.fullName ?? u.username}</b><div className="text-xs text-slate-500">{u.position ?? 'ไม่ระบุตำแหน่ง'} {u.isAllBranches ? '· ทุกสาขา' : ''} {u.isApprover ? '· APPROVER' : ''}</div></div>)}</div></section>
  </div>;
}
function DepartmentRow({ branchId, department, approvers }: { branchId: string; department: Department; approvers: User[] }) { const [hodId, setHodId] = useState(department.hodId ?? ''); const save = async () => { const response = await fetch(`/api/admin/departments/${department.id}/approval-config`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ branchId, hodId: hodId || null }) }); if (!response.ok) alert((await response.json()).error); }; return <div className="grid md:grid-cols-[1fr_1fr_auto] gap-3 items-center p-3 rounded-xl bg-slate-50 dark:bg-slate-800"><div><b>{department.name}</b><div className="text-xs text-slate-500">{department.code}</div></div><select className={selectClass} value={hodId} onChange={(e) => setHodId(e.target.value)}><option value="">ใช้ GM Fallback</option>{approvers.map((u) => <option key={u.id} value={u.id}>{u.fullName ?? u.username}</option>)}</select><button onClick={() => void save()} className="px-4 py-2 rounded-lg bg-blue-600 text-white">บันทึก</button></div>; }
