ALTER TABLE "AuditLog" ADD COLUMN "module" TEXT NOT NULL DEFAULT 'SYSTEM';

UPDATE "AuditLog"
SET "module" = 'E_APPROVE'
WHERE "entity" IN ('MEMO', 'MEMO_APPROVAL_STEP', 'APPROVAL_SIGNATURE', 'MEMO_ATTACHMENT', 'BRANCH', 'DEPARTMENT', 'MEMO_TYPE', 'SYSTEM_SETTING')
   OR "action" IN ('SUBMITTED', 'APPROVED_STEP', 'REVISION_REQUESTED', 'REPLACED_PENDING_APPROVER', 'RETRY_PDF', 'UPDATED_APPROVAL_CONFIG', 'UPDATED_REQUIRED_APPROVERS', 'ADDED_MEMO_ATTACHMENTS', 'DELETED_MEMO_ATTACHMENT');

UPDATE "AuditLog"
SET "module" = 'BORROW'
WHERE "entity" IN ('BORROW', 'BORROW_LOG');

UPDATE "AuditLog"
SET "module" = 'REPAIR'
WHERE "entity" = 'REPAIR';

UPDATE "AuditLog"
SET "module" = 'LICENSE'
WHERE "entity" = 'LICENSE';

UPDATE "AuditLog"
SET "module" = 'INVENTORY'
WHERE "entity" IN ('ASSET', 'CATEGORY', 'PROPERTY');

CREATE INDEX "AuditLog_module_createdAt_idx" ON "AuditLog"("module", "createdAt");
