'use client';
import { useState } from 'react';
import { CalendarDays, Mail, Save } from 'lucide-react';

export function NotificationPreferences({ email, initialEmail, initialCalendar }: { email: string | null; initialEmail: boolean; initialCalendar: boolean }) {
  const [emailEnabled, setEmailEnabled] = useState(initialEmail); const [calendarEnabled, setCalendarEnabled] = useState(initialCalendar); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  const save = async () => { setSaving(true); setMessage(''); const response = await fetch('/api/e-approve/notification-preferences', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ approvalEmailEnabled: emailEnabled, approvalCalendarEnabled: calendarEnabled }) }); const body = await response.json().catch(() => ({})); setMessage(response.ok ? 'บันทึกการแจ้งเตือนแล้ว' : body.error ?? 'บันทึกไม่สำเร็จ'); setSaving(false); };
  return <details className="mt-4 rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><summary className="cursor-pointer p-4 text-sm font-bold">ตั้งค่าการแจ้งเตือนของฉัน</summary><div className="space-y-3 border-t p-4 dark:border-slate-800"><p className="text-xs text-slate-500">อีเมลบัญชี: {email || 'ยังไม่ได้กำหนด'}</p><Toggle icon={Mail} label="อีเมลแจ้งเมื่อมี Memo ถึงคิว" checked={emailEnabled} onChange={setEmailEnabled}/><Toggle icon={CalendarDays} label="เพิ่มนัดหมายลง Calendar" checked={calendarEnabled} onChange={setCalendarEnabled}/><p className="text-xs text-slate-500">Calendar Invitation/Cancellation ถูกส่งผ่านอีเมล แม้ปิดอีเมลแจ้งเตือนทั่วไป</p>{message && <p className="text-xs font-bold text-blue-600">{message}</p>}<button onClick={() => void save()} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-60"><Save className="h-4 w-4"/>{saving ? 'กำลังบันทึก...' : 'บันทึก'}</button></div></details>;
}
function Toggle({ icon: Icon, label, checked, onChange }: { icon: typeof Mail; label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center justify-between rounded-xl border p-3 text-sm font-semibold dark:border-slate-700"><span className="flex items-center gap-2"><Icon className="h-4 w-4 text-blue-600"/>{label}</span><input type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} className="h-5 w-5 accent-blue-600"/></label>; }
