import Link from 'next/link';
import { redirect } from 'next/navigation';
import { getSession } from '@/lib/auth';
import prisma from '@/lib/prisma';
import { Building2, FileType2, Settings2, ShieldCheck, UsersRound, Workflow } from 'lucide-react';

export default async function EApproveAdminPage() {
  const session = await getSession(); if (session?.role !== 'ADMIN') redirect('/');
  const [branches, memoTypes, approvers, failedJobs] = await Promise.all([prisma.branch.count(), prisma.memoType.count(), prisma.user.count({ where: { isActive: true, isApprover: true } }), prisma.backgroundJob.count({ where: { status: 'FAILED' } })]);
  const cards = [{ href: '/e-approve/admin/branches', title: 'สาขา แผนก และ HOD/GM', description: 'แยกจัดการ Department และผู้อนุมัติตามแต่ละสาขา', icon: Building2, value: branches }, { href: '/e-approve/admin/approvers', title: 'Approvers & Branch Scope', description: 'กำหนดสิทธิ์ผู้อนุมัติและขอบเขตสาขาเฉพาะใน E‑Approve', icon: UsersRound, value: approvers }, { href: '/e-approve/admin/memo-types', title: 'Memo Types', description: 'จัดการประเภทเอกสารและ Required Approvers', icon: FileType2, value: memoTypes }, { href: '/e-approve/admin/system', title: 'System Settings', description: 'อีเมลกลางและข้อจำกัดไฟล์แนบ', icon: Settings2, value: null }, { href: '/e-approve/admin/audit-logs', title: 'Audit Logs & Operations', description: 'ตรวจสอบเหตุการณ์, PDF Jobs, Email และ Notifications', icon: ShieldCheck, value: failedJobs }];
  return <main className="min-h-full bg-slate-50 dark:bg-slate-950 p-5 md:p-8 w-full"><div className="max-w-6xl mx-auto"><header className="rounded-3xl bg-gradient-to-br from-blue-700 via-indigo-700 to-slate-900 p-8 text-white shadow-xl"><Workflow size={34}/><h1 className="mt-4 text-3xl font-bold">E‑Approve Administration</h1><p className="mt-2 text-blue-100">เลือกหัวข้อที่ต้องการจัดการ แต่ละส่วนถูกแยกเป็นหน้าของตัวเอง</p></header><div className="mt-6 grid md:grid-cols-2 gap-4">{cards.map(({ href, title, description, icon: Icon, value }) => <Link key={href} href={href} className="group rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-6 shadow-sm hover:-translate-y-0.5 hover:border-blue-400 hover:shadow-lg transition"><div className="flex items-start justify-between"><div className="rounded-xl bg-blue-50 dark:bg-blue-950 p-3 text-blue-600"><Icon/></div>{value !== null && <span className="text-3xl font-bold text-slate-300 group-hover:text-blue-600">{value}</span>}</div><h2 className="mt-5 text-lg font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></Link>)}</div></div></main>;
}
